import { Job, WorkerInfo } from '@/types';

export const INITIAL_MOCK_JOBS: Job[] = [
  {
    id: 'job-f4b821a9',
    type: 'IMAGE_RESIZE',
    status: 'COMPLETED',
    priority: 1,
    payload: {
      fileUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800',
      width: 400,
      height: 400,
    },
    retries: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    userId: 'usr-dev-1',
    resultUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=400',
    idempotencyKey: 'idem-img-001',
    logs: [
      {
        id: 'log-1',
        jobId: 'job-f4b821a9',
        workerId: 'worker-primary-1',
        event: 'PROCESSING',
        createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      },
      {
        id: 'log-2',
        jobId: 'job-f4b821a9',
        workerId: 'worker-primary-1',
        event: 'COMPLETED',
        duration: 1420,
        createdAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
      },
    ],
  },
  {
    id: 'job-89c02d1e',
    type: 'EMAIL',
    status: 'PROCESSING',
    priority: 1,
    payload: {
      to: 'team@company.com',
      subject: 'Weekly Pipeline Report',
      body: 'Processing weekly summary analytics...',
    },
    retries: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 1000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 10).toISOString(),
    userId: 'usr-dev-1',
    logs: [
      {
        id: 'log-3',
        jobId: 'job-89c02d1e',
        workerId: 'worker-primary-2',
        event: 'PROCESSING',
        createdAt: new Date(Date.now() - 1000 * 10).toISOString(),
      },
    ],
  },
  {
    id: 'job-33a789ef',
    type: 'DUMMY',
    status: 'RETRYING',
    priority: 0,
    payload: {
      duration: 3,
      failRate: 0.8,
    },
    retries: 1,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 1000 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 30).toISOString(),
    userId: 'usr-dev-1',
    lastError: 'Simulated connection timeout: socket hang up',
    logs: [
      {
        id: 'log-4',
        jobId: 'job-33a789ef',
        workerId: 'worker-primary-1',
        event: 'PROCESSING',
        createdAt: new Date(Date.now() - 1000 * 170).toISOString(),
      },
      {
        id: 'log-5',
        jobId: 'job-33a789ef',
        workerId: 'worker-primary-1',
        event: 'FAILED',
        duration: 3020,
        error: 'Simulated connection timeout: socket hang up',
        createdAt: new Date(Date.now() - 1000 * 167).toISOString(),
      },
      {
        id: 'log-6',
        jobId: 'job-33a789ef',
        workerId: 'worker-primary-1',
        event: 'RETRYING',
        duration: 2000,
        createdAt: new Date(Date.now() - 1000 * 165).toISOString(),
      },
    ],
  },
  {
    id: 'job-11b98ac2',
    type: 'DUMMY',
    status: 'DEAD_LETTER',
    priority: 0,
    payload: {
      duration: 2,
      failRate: 1.0,
    },
    retries: 3,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 1000 * 600).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 520).toISOString(),
    userId: 'usr-dev-1',
    lastError: 'Target executor exhausted 3 retry attempts: fatal mock error',
    logs: [
      {
        id: 'log-7',
        jobId: 'job-11b98ac2',
        workerId: 'worker-primary-2',
        event: 'DEAD_LETTER',
        error: 'Target executor exhausted 3 retry attempts: fatal mock error',
        createdAt: new Date(Date.now() - 1000 * 520).toISOString(),
      },
    ],
  },
  {
    id: 'job-a77b8104',
    type: 'EMAIL',
    status: 'WAITING',
    priority: 0,
    payload: {
      to: 'subscriber@newsletter.io',
      subject: 'Welcome to QueueCraft',
      body: 'Your account is verified and ready.',
    },
    retries: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 1000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 15).toISOString(),
    userId: 'usr-dev-1',
  },
];

export const INITIAL_MOCK_WORKERS: WorkerInfo[] = [
  {
    id: 'worker-primary-1',
    status: 'IDLE',
    lastHeartbeat: new Date(Date.now() - 1000 * 4).toISOString(),
    activeJobs: 0,
  },
  {
    id: 'worker-primary-2',
    status: 'BUSY',
    lastHeartbeat: new Date(Date.now() - 1000 * 2).toISOString(),
    activeJobs: 1,
  },
  {
    id: 'worker-secondary-3',
    status: 'IDLE',
    lastHeartbeat: new Date(Date.now() - 1000 * 18).toISOString(),
    activeJobs: 0,
  },
];
